server:
  port: 7070
spring:
  application:
    name: onlyoffice-tenant
  cache:
    type: hazelcast
  cloud:
    kubernetes:
      discovery:
        enabled: false
      config:
        enabled: false
    feign:
      client:
        onlyoffice-user-name: ${SPRING_CLOUD_FEIGN_ONLYOFFICE_USER_NAME:ONLYOFFICE-USER}
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 2250
            readTimeout: 3000
            loggerLevel: basic
  config:
    import:
      - "classpath:application-generic.yml"
      - "classpath:stream.yml"
  jpa:
    properties:
      hibernate:
        default_schema: tenants
  flyway:
    schemas: tenants
eureka:
  client:
    enabled: true
resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
        cancelRunningFuture: true
    instances:
      docSpaceClientTimeLimiter:
        baseConfig: default
      userServiceTimeLimiter:
        baseConfig: default
  circuitbreaker:
    configs:
      default:
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 100
        minimumNumberOfCalls: 60
        failureRateThreshold: 80
        permittedNumberOfCallsInHalfOpenState: 25
        waitDurationInOpenState: PT30S
        ignoreExceptions:
          - com.onlyoffice.tenant.exception.ServiceBadRequestException
    instances:
      docSpaceClientCircuitBreaker:
        baseConfig: default
      userServiceCircuitBreaker:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 250
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - com.onlyoffice.tenant.exception.ServiceBadRequestException
    instances:
      docSpaceClientRetry:
        baseConfig: default
      userServiceRetry:
        baseConfig: default
  ratelimiter:
    configs:
      defaultQuery:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      defaultCommand:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 50
    instances:
      findBoard:
        baseConfig: defaultQuery
      findTenant:
        baseConfig: defaultQuery
      registerDocSpace:
        baseConfig: defaultCommand
      registerRoom:
        baseConfig: defaultCommand
      registerTenant:
        baseConfig: defaultCommand
      removeRoom:
        baseConfig: defaultCommand
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 20
        maxWaitDuration: 500ms
    instances:
      docSpaceClientBulkhead:
        baseConfig: default
      userServiceBulkhead:
        baseConfig: default
info:
  app:
    name: "onlyoffice-tenant"
    description: "ONLYOFFICE x Monday Tenant Service"
    version: "1.0.0"